In [1]:
import os
import pandas as pd
import nltk
import numpy as np
import sklearn
from textblob import TextBlob
import re

In [12]:
data = pd.read_csv("data bocor-new1.csv") 
data.head()

time                   id                  username  \
0  2021-11-21 23:56:14+00:00  1462570580775821313               BukanBuTejo   
1  2021-11-21 16:35:53+00:00  1462459765494214661  Syan~GA ALBUM~CEK PINNED   
2  2021-11-21 14:52:08+00:00  1462433655008030720           Ivoox Indonesia   
3  2021-11-21 14:41:13+00:00  1462430907277529095          🦈 SUROBOYOFESS 🐊   
4  2021-11-21 11:44:12+00:00  1462386359386222594           Aktual Official   

                                                text  
0  b'@txtdaritekno Gak usah sok keren data bocor ...  
1  b'@ameamakunai Bisa aja email kak ame bocor tr...  
2  b'Data yang Bocor Berpotensi Disalahgunakan Pe...  
3  b'Kok data lu bocor yaa?? Hmm isok ae lak mbuj...  
4  b'CISSReC Sebut Data Pribadi Bocor Bisa Diguna...

In [15]:
#pelabelan dengan textblob

# Casefolding

def text_blop(txt):
    clean = ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)"," ",txt).split())
    text = TextBlob(clean)
    
    try:
      text = text.translate(to="en")
    except Exception as e:
      print(e)

    if text.sentiment.polarity > 0.0:
      hasil = "Positif"
    
    elif text.sentiment.polarity == 0.0:
      hasil = "Netral"

    else:
      hasil = "Negatif"

    return hasil

data['label'] = data['text'].apply(lambda x: text_blop(x))
data.head()    

Translation API returned the input string unchanged.
Translation API returned the input string unchanged.
Translation API returned the input string unchanged.
Translation API returned the input string unchanged.
Translation API returned the input string unchanged.
Translation API returned the input string unchanged.
Translation API returned the input string unchanged.


time                   id                  username  \
0  2021-11-21 23:56:14+00:00  1462570580775821313               BukanBuTejo   
1  2021-11-21 16:35:53+00:00  1462459765494214661  Syan~GA ALBUM~CEK PINNED   
2  2021-11-21 14:52:08+00:00  1462433655008030720           Ivoox Indonesia   
3  2021-11-21 14:41:13+00:00  1462430907277529095          🦈 SUROBOYOFESS 🐊   
4  2021-11-21 11:44:12+00:00  1462386359386222594           Aktual Official   

                                                text    label  
0  b'@txtdaritekno Gak usah sok keren data bocor ...  Positif  
1  b'@ameamakunai Bisa aja email kak ame bocor tr...  Positif  
2  b'Data yang Bocor Berpotensi Disalahgunakan Pe...   Netral  
3  b'Kok data lu bocor yaa?? Hmm isok ae lak mbuj...   Netral  
4  b'CISSReC Sebut Data Pribadi Bocor Bisa Diguna...   Netral

In [16]:
tweet_positif = [t for t in data if t['label']=="Positif"]
tweet_negatif = [t for t in data if t['label']=="Negatif"]
tweet_netral = [t for t in data if t['label']=="Netral"]

TypeError: string indices must be integers

In [17]:
# Casefolding

def casefolding(txt):
    text = str(txt).lower()
    return text

data['text'] = data['text'].apply(lambda x: casefolding(x))
data.head()

time                   id                  username  \
0  2021-11-21 23:56:14+00:00  1462570580775821313               BukanBuTejo   
1  2021-11-21 16:35:53+00:00  1462459765494214661  Syan~GA ALBUM~CEK PINNED   
2  2021-11-21 14:52:08+00:00  1462433655008030720           Ivoox Indonesia   
3  2021-11-21 14:41:13+00:00  1462430907277529095          🦈 SUROBOYOFESS 🐊   
4  2021-11-21 11:44:12+00:00  1462386359386222594           Aktual Official   

                                                text    label  
0  b'@txtdaritekno gak usah sok keren data bocor ...  Positif  
1  b'@ameamakunai bisa aja email kak ame bocor tr...  Positif  
2  b'data yang bocor berpotensi disalahgunakan pe...   Netral  
3  b'kok data lu bocor yaa?? hmm isok ae lak mbuj...   Netral  
4  b'cissrec sebut data pribadi bocor bisa diguna...   Netral

In [18]:
import string
import re
string.punctuation

def remove_punctuation(txt):
    '''a function for removing punctuation'''
    text = re.sub('\[.*?\]', '', str(txt))
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\w*\d\w*', '', text)
    text = re.sub('[‘’“”…]', '', text)
    text = re.sub('\n', '', text)
    return text

data['clean'] = data['text'].apply(lambda x: remove_punctuation(x))
data.head()

time                   id                  username  \
0  2021-11-21 23:56:14+00:00  1462570580775821313               BukanBuTejo   
1  2021-11-21 16:35:53+00:00  1462459765494214661  Syan~GA ALBUM~CEK PINNED   
2  2021-11-21 14:52:08+00:00  1462433655008030720           Ivoox Indonesia   
3  2021-11-21 14:41:13+00:00  1462430907277529095          🦈 SUROBOYOFESS 🐊   
4  2021-11-21 11:44:12+00:00  1462386359386222594           Aktual Official   

                                                text    label  \
0  b'@txtdaritekno gak usah sok keren data bocor ...  Positif   
1  b'@ameamakunai bisa aja email kak ame bocor tr...  Positif   
2  b'data yang bocor berpotensi disalahgunakan pe...   Netral   
3  b'kok data lu bocor yaa?? hmm isok ae lak mbuj...   Netral   
4  b'cissrec sebut data pribadi bocor bisa diguna...   Netral   

                                               clean  
0  btxtdaritekno gak usah sok keren data bocor di...  
1  bameamakunai bisa aja email kak ame bocor trus...  
2  bdata yang bocor berpotensi disalahgunakan pel...  
3  bkok data lu bocor yaa hmm isok ae lak mbujuki...  
4  bcissrec sebut data pribadi bocor bisa  httpst...

In [19]:
# Stemming

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stemming(txt):
    words=stemmer.stem(txt)
    return words

data['stemming']=data['clean'].apply(lambda x: stemming(x))

In [20]:
data.head()

time                   id                  username  \
0  2021-11-21 23:56:14+00:00  1462570580775821313               BukanBuTejo   
1  2021-11-21 16:35:53+00:00  1462459765494214661  Syan~GA ALBUM~CEK PINNED   
2  2021-11-21 14:52:08+00:00  1462433655008030720           Ivoox Indonesia   
3  2021-11-21 14:41:13+00:00  1462430907277529095          🦈 SUROBOYOFESS 🐊   
4  2021-11-21 11:44:12+00:00  1462386359386222594           Aktual Official   

                                                text    label  \
0  b'@txtdaritekno gak usah sok keren data bocor ...  Positif   
1  b'@ameamakunai bisa aja email kak ame bocor tr...  Positif   
2  b'data yang bocor berpotensi disalahgunakan pe...   Netral   
3  b'kok data lu bocor yaa?? hmm isok ae lak mbuj...   Netral   
4  b'cissrec sebut data pribadi bocor bisa diguna...   Netral   

                                               clean  \
0  btxtdaritekno gak usah sok keren data bocor di...   
1  bameamakunai bisa aja email kak ame bocor trus...   
2  bdata yang bocor berpotensi disalahgunakan pel...   
3  bkok data lu bocor yaa hmm isok ae lak mbujuki...   
4  bcissrec sebut data pribadi bocor bisa  httpst...   

                                            stemming  
0  btxtdaritekno gak usah sok keren data bocor di...  
1  bameamakunai bisa aja email kak ame bocor trus...  
2  bdata yang bocor potensi disalahgunakan laku t...  
3  bkok data lu bocor yaa hmm isok ae lak mbujuki...  
4  bcissrec sebut data pribadi bocor bisa httpstc...

In [21]:
# Filtering & Tokenizing

from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from nltk.tokenize import word_tokenize

factory = StopWordRemoverFactory()
stopword = factory.create_stop_word_remover()

def filtering(txt):
    stop = stopword.remove(txt)
    tokens = nltk.tokenize.word_tokenize(stop)
    return tokens

data['filter'] = data['stemming'].apply(lambda x: filtering(x))
data.head()

time                   id                  username  \
0  2021-11-21 23:56:14+00:00  1462570580775821313               BukanBuTejo   
1  2021-11-21 16:35:53+00:00  1462459765494214661  Syan~GA ALBUM~CEK PINNED   
2  2021-11-21 14:52:08+00:00  1462433655008030720           Ivoox Indonesia   
3  2021-11-21 14:41:13+00:00  1462430907277529095          🦈 SUROBOYOFESS 🐊   
4  2021-11-21 11:44:12+00:00  1462386359386222594           Aktual Official   

                                                text    label  \
0  b'@txtdaritekno gak usah sok keren data bocor ...  Positif   
1  b'@ameamakunai bisa aja email kak ame bocor tr...  Positif   
2  b'data yang bocor berpotensi disalahgunakan pe...   Netral   
3  b'kok data lu bocor yaa?? hmm isok ae lak mbuj...   Netral   
4  b'cissrec sebut data pribadi bocor bisa diguna...   Netral   

                                               clean  \
0  btxtdaritekno gak usah sok keren data bocor di...   
1  bameamakunai bisa aja email kak ame bocor trus...   
2  bdata yang bocor berpotensi disalahgunakan pel...   
3  bkok data lu bocor yaa hmm isok ae lak mbujuki...   
4  bcissrec sebut data pribadi bocor bisa  httpst...   

                                            stemming  \
0  btxtdaritekno gak usah sok keren data bocor di...   
1  bameamakunai bisa aja email kak ame bocor trus...   
2  bdata yang bocor potensi disalahgunakan laku t...   
3  bkok data lu bocor yaa hmm isok ae lak mbujuki...   
4  bcissrec sebut data pribadi bocor bisa httpstc...   

                                              filter  
0  [btxtdaritekno, gak, usah, sok, keren, data, b...  
1  [bameamakunai, aja, email, kak, ame, bocor, tr...  
2  [bdata, bocor, potensi, disalahgunakan, laku, ...  
3  [bkok, data, lu, bocor, yaa, hmm, isok, ae, la...  
4  [bcissrec, sebut, data, pribadi, bocor, httpst...

In [22]:
#as our "lam_words column is column of lists, and not text. 
#Tfidf Vectorizer works on text so convert this column into string"

data['filter']=[" ".join(review) for review in data['filter'].values]

In [23]:
# # split data into sets
# train 80% test 20%

from sklearn import model_selection, svm
Train_X, Test_X, Train_Y, Test_Y = model_selection.train_test_split(data['filter'],data['label'],test_size=0.2)

In [24]:
# # Encoding

from sklearn.preprocessing import LabelEncoder
Encoder = LabelEncoder()
Train_Y = Encoder.fit_transform(Train_Y)
Test_Y = Encoder.fit_transform(Test_Y)

In [25]:
# Word Vectorization

from sklearn.feature_extraction.text import TfidfVectorizer

Tfidf_vect = TfidfVectorizer(max_features=5000)
Tfidf_vect.fit(data['filter'])
Train_X_Tfidf = Tfidf_vect.transform(Train_X)
Test_X_Tfidf = Tfidf_vect.transform(Test_X)

In [26]:
print(Train_X_Tfidf)

  (0, 1083)	0.5159662452949091
  (0, 1031)	0.44387311540602853
  (0, 931)	0.23258708785891538
  (0, 877)	0.4927574413353145
  (0, 229)	0.1149667797320975
  (0, 125)	0.34349659459908793
  (0, 40)	0.32960820797253326
  (1, 1122)	0.47125262332890966
  (1, 1088)	0.37261026981996936
  (1, 931)	0.200787260564206
  (1, 556)	0.42538654092595524
  (1, 348)	0.10564683824366138
  (1, 229)	0.09924826425574726
  (1, 144)	0.44542218525564137
  (1, 17)	0.44542218525564137
  (2, 1259)	0.3737545636498834
  (2, 1242)	0.16396706438699035
  (2, 1164)	0.17347566374037224
  (2, 1121)	0.17347566374037224
  (2, 1103)	0.1868772818249417
  (2, 996)	0.1868772818249417
  (2, 995)	0.1868772818249417
  (2, 973)	0.1868772818249417
  (2, 922)	0.1868772818249417
  (2, 921)	0.1868772818249417
  :	:
  (164, 239)	0.3970328229340025
  (164, 229)	0.09263296963506462
  (164, 26)	0.2944762807092921
  (165, 1198)	0.3886105391547094
  (165, 956)	0.5294579641683231
  (165, 811)	0.5294579641683231
  (165, 340)	0.4265798062498096

In [27]:
# Use SVM

from sklearn import model_selection, svm
from sklearn.metrics import accuracy_score

In [28]:
# fit the training dataset on the classifier
SVM = svm.SVC(C=1.0, kernel='linear', degree=3, gamma='auto')
SVM.fit(Train_X_Tfidf,Train_Y)

# predict the labels on validation dataset
predictions_SVM = SVM.predict(Test_X_Tfidf)

In [29]:
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Test_Y, predictions_SVM)

In [30]:
print(cm)
# Use accuracy_score function to get the accuracy
print("SVM Accuracy Score -> ",accuracy_score(predictions_SVM, Test_Y)*100)

[[ 1  4  2]
 [ 2 10  8]
 [ 0  2 13]]
SVM Accuracy Score ->  57.14285714285714


In [31]:
from sklearn.metrics import classification_report

print(classification_report(Test_Y, predictions_SVM))

              precision    recall  f1-score   support

           0       0.33      0.14      0.20         7
           1       0.62      0.50      0.56        20
           2       0.57      0.87      0.68        15

    accuracy                           0.57        42
   macro avg       0.51      0.50      0.48        42
weighted avg       0.56      0.57      0.54        42



In [32]:
from sklearn import model_selection, naive_bayes

# fit the training dataset on the NB classifier
Naive = naive_bayes.MultinomialNB()
Naive.fit(Train_X_Tfidf,Train_Y)
# predict the labels on validation dataset
predictions_NB = Naive.predict(Test_X_Tfidf)
# Use accuracy_score function to get the accuracy
print("Naive Bayes Accuracy Score ->",accuracy_score(predictions_NB, Test_Y)*100)

Naive Bayes Accuracy Score -> 59.523809523809526


In [33]:
from sklearn.metrics import classification_report

print(classification_report(Test_Y, predictions_NB))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         7
           1       0.62      0.65      0.63        20
           2       0.57      0.80      0.67        15

    accuracy                           0.60        42
   macro avg       0.40      0.48      0.43        42
weighted avg       0.50      0.60      0.54        42



C:\Users\ZENBOOK\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
