In [25]:
import os
import pandas as pd
import nltk
import numpy as np
import sklearn
from textblob import TextBlob
import re

In [21]:
data = pd.read_csv("data leak-new2.csv") 

In [22]:
data

time                   id                username  \
0     2021-11-20 19:02:11+00:00  1462134194188873729             Matt Ridley   
1     2021-11-20 20:04:42+00:00  1462149924993257477            Sarah Kimani   
2     2021-11-19 13:04:53+00:00  1461681888263876610         BBC News Africa   
3     2021-11-21 23:31:12+00:00  1462564282760151043         Laura Henderson   
4     2021-11-21 22:00:37+00:00  1462541485153394688            Engin Dikmen   
...                         ...                  ...                     ...   
1056  2021-11-13 14:53:50+00:00  1459534980447719428          Ron Roozendaal   
1057  2021-11-13 14:30:31+00:00  1459529111102177280               Marc Ruef   
1058  2021-11-13 14:19:19+00:00  1459526290550177799  Pamalot #CorbynKnights   
1059  2021-11-13 14:14:49+00:00  1459525161686863875                    Neph   
1060  2021-11-13 13:56:07+00:00  1459520455874908167                    René   

                                                   text  
0     b'Now that we know the US government was fundi...  
1     b'What is \xe2\x80\x9cCongo Hold-up,\xe2\x80\x...  
2     b"\xf0\x9f\x87\xa8\xf0\x9f\x87\xa9 Companies o...  
3     b'@DeVos1990 @Bob_Wachter There are very few p...  
4     b'The Scale Of The Pandora Papers Leak\n\n#Pan...  
...                                                 ...  
1056  b'Daar gaat je vertrouwen in de goedheid van m...  
1057  b'Somebody is selling employee data and other ...  
1058  b'Apparently I got an update on the deleted uk...  
1059  b'@Lilitheos YO FELLOW EITRI FAN\n\nI assume h...  
1060  b'@mvp2536 @drownedingin Mne nejde o to \xc4\x...  

[1061 rows x 4 columns]

In [29]:
#pelabelan dengan textblob

# Casefolding

def text_blop(txt):
    clean = ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)"," ",txt).split())
    text = TextBlob(clean)

    if text.sentiment.polarity > 0.0:
      hasil = "Positif"
    
    elif text.sentiment.polarity == 0.0:
      hasil = "Netral"

    else:
      hasil = "Negatif"

    return hasil

data['label'] = data['text'].apply(lambda x: text_blop(x))
data.head()    

time                   id         username  \
0  2021-11-20 19:02:11+00:00  1462134194188873729      Matt Ridley   
1  2021-11-20 20:04:42+00:00  1462149924993257477     Sarah Kimani   
2  2021-11-19 13:04:53+00:00  1461681888263876610  BBC News Africa   
3  2021-11-21 23:31:12+00:00  1462564282760151043  Laura Henderson   
4  2021-11-21 22:00:37+00:00  1462541485153394688     Engin Dikmen   

                                                text    label  
0  b'Now that we know the US government was fundi...  Positif  
1  b'What is \xe2\x80\x9cCongo Hold-up,\xe2\x80\x...   Netral  
2  b"\xf0\x9f\x87\xa8\xf0\x9f\x87\xa9 Companies o...   Netral  
3  b'@DeVos1990 @Bob_Wachter There are very few p...  Positif  
4  b'The Scale Of The Pandora Papers Leak\n\n#Pan...   Netral

In [30]:
# Casefolding

def casefolding(txt):
    text = str(txt).lower()
    return text

data['text'] = data['text'].apply(lambda x: casefolding(x))
data.head()

time                   id         username  \
0  2021-11-20 19:02:11+00:00  1462134194188873729      Matt Ridley   
1  2021-11-20 20:04:42+00:00  1462149924993257477     Sarah Kimani   
2  2021-11-19 13:04:53+00:00  1461681888263876610  BBC News Africa   
3  2021-11-21 23:31:12+00:00  1462564282760151043  Laura Henderson   
4  2021-11-21 22:00:37+00:00  1462541485153394688     Engin Dikmen   

                                                text    label  
0  b'now that we know the us government was fundi...  Positif  
1  b'what is \xe2\x80\x9ccongo hold-up,\xe2\x80\x...   Netral  
2  b"\xf0\x9f\x87\xa8\xf0\x9f\x87\xa9 companies o...   Netral  
3  b'@devos1990 @bob_wachter there are very few p...  Positif  
4  b'the scale of the pandora papers leak\n\n#pan...   Netral

In [31]:
# Removing Punctuationtrain

import string
import re
string.punctuation

def remove_punctuation(txt):
    '''a function for removing punctuation'''
    text = re.sub('\[.*?\]', '', str(txt))
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\w*\d\w*', '', text)
    text = re.sub('[‘’“”…]', '', text)
    text = re.sub('\n', '', text)
    return text

data['clean'] = data['text'].apply(lambda x: remove_punctuation(x))
data.head()

time                   id         username  \
0  2021-11-20 19:02:11+00:00  1462134194188873729      Matt Ridley   
1  2021-11-20 20:04:42+00:00  1462149924993257477     Sarah Kimani   
2  2021-11-19 13:04:53+00:00  1461681888263876610  BBC News Africa   
3  2021-11-21 23:31:12+00:00  1462564282760151043  Laura Henderson   
4  2021-11-21 22:00:37+00:00  1462541485153394688     Engin Dikmen   

                                                text    label  \
0  b'now that we know the us government was fundi...  Positif   
1  b'what is \xe2\x80\x9ccongo hold-up,\xe2\x80\x...   Netral   
2  b"\xf0\x9f\x87\xa8\xf0\x9f\x87\xa9 companies o...   Netral   
3  b'@devos1990 @bob_wachter there are very few p...  Positif   
4  b'the scale of the pandora papers leak\n\n#pan...   Netral   

                                               clean  
0  bnow that we know the us government was fundin...  
1  bwhat is    biggest financial data leak  via l...  
2   companies owned by family and friends of form...  
3   bobwachter there are very few professionals i...  
4  bthe scale of the pandora papers leaknnpandora...

In [32]:
# Stemming

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stemming(txt):
    words=stemmer.stem(txt)
    return words

data['stemming']=data['clean'].apply(lambda x: stemming(x))

In [34]:
# Filtering & Tokenizing

from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from nltk.tokenize import word_tokenize

factory = StopWordRemoverFactory()
stopword = factory.create_stop_word_remover()

def filtering(txt):
    stop = stopword.remove(txt)
    tokens = nltk.tokenize.word_tokenize(stop)
    return tokens

data['filter'] = data['stemming'].apply(lambda x: filtering(x))
data.head()

time                   id         username  \
0  2021-11-20 19:02:11+00:00  1462134194188873729      Matt Ridley   
1  2021-11-20 20:04:42+00:00  1462149924993257477     Sarah Kimani   
2  2021-11-19 13:04:53+00:00  1461681888263876610  BBC News Africa   
3  2021-11-21 23:31:12+00:00  1462564282760151043  Laura Henderson   
4  2021-11-21 22:00:37+00:00  1462541485153394688     Engin Dikmen   

                                                text    label  \
0  b'now that we know the us government was fundi...  Positif   
1  b'what is \xe2\x80\x9ccongo hold-up,\xe2\x80\x...   Netral   
2  b"\xf0\x9f\x87\xa8\xf0\x9f\x87\xa9 companies o...   Netral   
3  b'@devos1990 @bob_wachter there are very few p...  Positif   
4  b'the scale of the pandora papers leak\n\n#pan...   Netral   

                                               clean  \
0  bnow that we know the us government was fundin...   
1  bwhat is    biggest financial data leak  via l...   
2   companies owned by family and friends of form...   
3   bobwachter there are very few professionals i...   
4  bthe scale of the pandora papers leaknnpandora...   

                                            stemming  \
0  bnow that we know the us government was fundin...   
1  bwhat is biggest financial data leak via lorie...   
2  companies owned by family and friends of forme...   
3  bobwachter there are very few professionals in...   
4  bthe scale of the pandora papers leaknnpandora...   

                                              filter  
0  [bnow, that, we, know, the, us, government, wa...  
1  [bwhat, is, biggest, financial, data, leak, vi...  
2  [companies, owned, by, family, and, friends, o...  
3  [bobwachter, there, are, very, few, profession...  
4  [bthe, scale, of, the, pandora, papers, leaknn...

In [35]:
#as our "lam_words column is column of lists, and not text. 
#Tfidf Vectorizer works on text so convert this column into string"

data['filter']=[" ".join(review) for review in data['filter'].values]

In [36]:
# # split data into sets
# train 80% test 20%

from sklearn import model_selection, svm
Train_X, Test_X, Train_Y, Test_Y = model_selection.train_test_split(data['filter'],data['label'],test_size=0.2)

In [37]:
# # Encoding

from sklearn.preprocessing import LabelEncoder
Encoder = LabelEncoder()
Train_Y = Encoder.fit_transform(Train_Y)
Test_Y = Encoder.fit_transform(Test_Y)

In [38]:
# Word Vectorization

from sklearn.feature_extraction.text import TfidfVectorizer

Tfidf_vect = TfidfVectorizer(max_features=5000)
Tfidf_vect.fit(data['filter'])
Train_X_Tfidf = Tfidf_vect.transform(Train_X)
Test_X_Tfidf = Tfidf_vect.transform(Test_X)

In [39]:
print(Train_X_Tfidf)

  (0, 4488)	0.3619344794707803
  (0, 4436)	0.2151869565459247
  (0, 2680)	0.32910787737896763
  (0, 2458)	0.1558073911777884
  (0, 2413)	0.35361538813320975
  (0, 2407)	0.343095041404924
  (0, 1581)	0.14652436474633979
  (0, 1393)	0.3458151141718577
  (0, 529)	0.38985384792293154
  (0, 155)	0.39282122224826765
  (1, 4337)	0.1526648585307957
  (1, 3463)	0.2695412222654442
  (1, 3385)	0.28220619654295054
  (1, 3084)	0.28220619654295054
  (1, 2630)	0.26517313902656686
  (1, 2458)	0.07067841111427442
  (1, 2312)	0.24577645026341655
  (1, 2208)	0.13365047668610316
  (1, 2103)	0.41289418103897385
  (1, 1977)	0.18918154442985802
  (1, 1943)	0.24577645026341655
  (1, 1581)	0.06646738137077574
  (1, 1561)	0.30245002148797095
  (1, 1328)	0.2767966699467436
  (1, 866)	0.2794370097546169
  :	:
  (846, 4719)	0.35249455491216003
  (846, 4692)	0.3169260520522898
  (846, 4389)	0.16235334733973253
  (846, 4339)	0.10065627279971023
  (846, 3095)	0.25264114333828336
  (846, 2781)	0.19708744965762312
  (8

In [40]:
# Use SVM

from sklearn import model_selection, svm
from sklearn.metrics import accuracy_score

In [41]:
# fit the training dataset on the classifier
SVM = svm.SVC(C=1.0, kernel='linear', degree=3, gamma='auto')
SVM.fit(Train_X_Tfidf,Train_Y)

# predict the labels on validation dataset
predictions_SVM = SVM.predict(Test_X_Tfidf)

In [42]:
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Test_Y, predictions_SVM)

In [43]:
print(cm)

[[ 4 11 10]
 [ 4 93 10]
 [ 2 15 64]]


In [44]:
# Use accuracy_score function to get the accuracy
print("SVM Accuracy Score -> ",accuracy_score(predictions_SVM, Test_Y)*100)

SVM Accuracy Score ->  75.5868544600939


In [46]:
from sklearn.metrics import classification_report

print(classification_report(Test_Y, predictions_SVM))

              precision    recall  f1-score   support

           0       0.40      0.16      0.23        25
           1       0.78      0.87      0.82       107
           2       0.76      0.79      0.78        81

    accuracy                           0.76       213
   macro avg       0.65      0.61      0.61       213
weighted avg       0.73      0.76      0.74       213



In [63]:
from sklearn import model_selection, naive_bayes

# fit the training dataset on the NB classifier
Naive = naive_bayes.MultinomialNB()
Naive.fit(Train_X_Tfidf,Train_Y)
# predict the labels on validation dataset
predictions_NB = Naive.predict(Test_X_Tfidf)
# Use accuracy_score function to get the accuracy
print("Naive Bayes Accuracy Score ->",accuracy_score(predictions_NB, Test_Y)*100)

Naive Bayes Accuracy Score -> 70.89201877934272


In [65]:
from sklearn.metrics import classification_report

print(classification_report(Test_Y, predictions_NB))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        25
           1       0.76      0.84      0.80       107
           2       0.64      0.75      0.69        81

    accuracy                           0.71       213
   macro avg       0.47      0.53      0.50       213
weighted avg       0.63      0.71      0.67       213



C:\Users\ZENBOOK\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
